# GitHub Actions workflow for building and pushing Docker images and syncing README
name: Build/Push Docker images

on:
  # Trigger the workflow manually or when code is pushed to the 'main' branch
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'release'

jobs:
  # Job to push the release Docker image to multiple registries
  push_to_release_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Step 1: Check out the repository code
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Extract metadata about the Docker image
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            thetestgame/astron
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      # Step 3: Log in to DockerHub (only if not a pull request)
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "BUILD_TYPE=Release"

      # Step 5: Sync GitHub README with DockerHub repository README
      - name: Sync GitHub README
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thetestgame/astron
          readme: "./README.md"

  # Job to push the debug Docker image to multiple registries
  push_to_debug_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Step 1: Check out the repository code
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Log in to DockerHub (only if not a pull request)
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: debug
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "BUILD_TYPE=DEBUG"